app.ts, docs/doc, utils/nomenclature.ts
feat: uCamelCase & camelCase utils
=> feat: uCamelCase & camelCase utils

app.ts, modules/db.ts, processes/getDataOfBD.ts, templates/vue/views/index, types/index.ts
fix: tableDetailForeignKeysAssoc & tableForeignKeysAssocMasterDetail
=> fix: tableDetailForeignKeysAssoc & tableForeignKeysAssocMasterDetail

app.ts, modules/renderings/vue/createOrEditMaster.ts, modules/renderings/vue/tabs.ts, processes/writeFrontend.ts, templates/vue/views/createOrEditMaster, templates/vue/views/index, templates/vue/views/tabs
feat: createOrEditMaster & tabs
=> feat: createOrEditMaster & tabs

app.ts, modules/renderings/vue/createOrEditMaster.ts, modules/renderings/vue/datagrid.ts, modules/renderings/vue/index.ts, modules/renderings/vue/tabs.ts, processes/getDataOfBD.ts, processes/writeFrontend.ts, templates/vue/views/tabs, types/index.ts, types/utilsRendering.ts, utils/rendering.ts
=> refactor: Boilerplate code

.env.example, .gitignore, src/config/output.ts, src/utils/rendering.ts
feat: Output the app folder outside project directory
=> feat: Output the app folder outside project directory

.env.example, src/app.ts, src/config/crud.ts, src/config/output.ts, src/customTypes/utilsRendering.ts, src/modules/renderings/vue/createOrEditMaster.ts, src/modules/renderings/vue/datagrid.ts, src/modules/renderings/vue/tabs.ts, src/processes/writeBackend.ts, src/utils/rendering.ts
feat: Allow two output paths, for the back and the front.
=> feat: Allow two output paths

src/modules/renderings/laravel/controller.ts, src/modules/renderings/vue/createOrEditMaster.ts, src/modules/renderings/vue/datagrid.ts, src/modules/renderings/vue/tabs.ts, src/utils/createOutputPath.ts, src/utils/rendering.ts
feat: Recursive function that validates if the folder or file exists
=> feat: Recursive function that validates if the folder or file exists

package-lock.json, package.json, src/customTypes/utilsRendering.ts, src/modules/renderings/laravel/controller.ts, src/modules/renderings/vue/createOrEditMaster.ts, src/modules/renderings/vue/datagrid.ts, src/modules/renderings/vue/tabs.ts, src/processes/writeBackend.ts, src/processes/writeFrontend.ts, src/utils/rendering.ts
=> feat: Reorder custom types

src/modules/db.ts, src/processes/getDataOfBD.ts
fix: Validate if table master exist
=> fix: Validate if table master exist

src/modules/renderings/laravel/index.ts, src/modules/renderings/laravel/serviceIndex.ts, src/processes/writeBackend.ts, src/templates/laravel/serviceIndex
feat: Created the Laravel/App/Services/Index template.
=> feat: Created the Laravel/App/Services/Index template

src/modules/renderings/laravel/index.ts, src/modules/renderings/laravel/serviceStore.ts, src/processes/writeBackend.ts, src/templates/laravel/model, src/templates/laravel/serviceStore
feat: Created the Laravel/App/Services/Store template.
=> feat: Created the Laravel/App/Services/Store template

src/modules/renderings/laravel/index.ts, src/modules/renderings/laravel/serviceUpdate.ts, src/processes/writeBackend.ts, src/templates/laravel/serviceStore, src/templates/laravel/serviceUpdate
feat: Create the Laravel/App/Services/Update template.
=> feat: Create the Laravel/App/Services/Update template

src/modules/renderings/laravel/index.ts, src/modules/renderings/laravel/resource.ts, src/processes/writeBackend.ts, src/templates/laravel/resource
feat: Create the Laravel/App/Resources template
=> feat: Create the Laravel/App/Resources template

src/modules/renderings/laravel/index.ts, src/modules/renderings/laravel/requestStore.ts, src/modules/renderings/laravel/requestUpdate.ts, src/modules/renderings/laravel/serviceIndex.ts, src/modules/renderings/laravel/serviceUpdate.ts, src/processes/writeBackend.ts, src/templates/laravel/requestStore, src/templates/laravel/requestUpdate, src/templates/laravel/resource, src/templates/laravel/serviceIndex
feat: Create the Laravel/App/Requests/Stores&Update template.
=> feat: Create the Laravel/App/Requests/Stores&Update template

src/modules/renderings/laravel/index.ts, src/modules/renderings/laravel/route.ts, src/processes/writeBackend.ts, src/templates/laravel/route
feat: Create the Laravel code: Routes.
=> feat: Create the Laravel code: Routes

src/templates/vue/components/formCreateOrEditMaster
feat: Buid FormCreateOrEdit template for Vue
=> feat: Buid FormCreateOrEdit template for Vue

src/modules/renderings/vue/datagrid.ts, src/modules/renderings/vue/formCreateOrEditMaster.ts, src/modules/renderings/vue/index.ts, src/modules/renderings/vue/routes.ts, src/modules/renderings/vue/services.ts, src/modules/renderings/vue/tabs.ts, src/processes/writeFrontend.ts, src/templates/vue/routes/index, src/templates/vue/services/index, src/templates/vue/views/createOrEditMaster, src/templates/vue/views/index, src/templates/vue/views/tabs
feat: Build index services and index routes for Vue.
=> feat: Build index services and index routes for Vue

src/modules/renderings/vue/index.ts, src/modules/renderings/vue/types.ts, src/processes/writeFrontend.ts, src/templates/vue/types/index
feat: Build index types for Vue.
=> feat: Build index types for Vue

src/modules/renderings/vue/index.ts, src/modules/renderings/vue/useCreateOrEditMaster.ts, src/modules/renderings/vue/useDatagrid.ts, src/processes/writeFrontend.ts, src/templates/vue/composables/useCreateOrEdit, src/templates/vue/composables/useIndex
feat: Build useIndex and useCreateOrEdit composables for Vue.
=> feat: Build useIndex and useCreateOrEdit composables for Vue

src/modules/renderings/laravel/controller.ts, src/modules/renderings/laravel/model.ts, src/modules/renderings/laravel/requestStore.ts, src/modules/renderings/laravel/requestUpdate.ts, src/modules/renderings/laravel/resource.ts, src/modules/renderings/laravel/route.ts, src/modules/renderings/laravel/serviceIndex.ts, src/modules/renderings/laravel/serviceStore.ts, src/modules/renderings/laravel/serviceUpdate.ts, src/templates/laravel/controller, src/templates/laravel/model, src/templates/laravel/requestStore, src/templates/laravel/requestUpdate, src/templates/laravel/resource, src/templates/laravel/route, src/templates/laravel/serviceIndex, src/templates/laravel/serviceStore, src/templates/laravel/serviceUpdate, src/templates/vue/components/formCreateOrEditMaster, src/templates/vue/composables/useCreateOrEdit, src/templates/vue/views/createOrEditMaster, src/templates/vue/views/index
=> feat: First hot test

src/templates/vue/views/index
=> fix: Color of remove button

src/app.ts, src/modules/renderings/vue/formCreateOrEditMaster.ts, src/processes/writeBackend.ts, src/processes/writeFrontend.ts
refactor: App, WriteBackend and WriteFrontend.
=> refactor: App, WriteBackend and WriteFrontend

package-lock.json, package.json
chore: Update nodemon package.
=> chore: Update nodemon package

package-lock.json, package.json, src/config/output.ts, src/customTypes/utilsRendering.ts, src/processes/writeBackend.ts, src/processes/writeFrontend.ts, src/utils/rendering.ts
feat: Add colors when displaying output.
=> feat: Add colors when displaying output

src/templates/laravel/controller, src/templates/laravel/route
feat: Add route and controller help.
=> feat: Add route and controller help

src/app.ts, src/customTypes/db.ts, src/customTypes/utilsRendering.ts, src/modules/renderings/laravel/core/controller.ts, src/modules/renderings/laravel/core/model.ts, src/modules/renderings/laravel/core/requestStore.ts, src/modules/renderings/laravel/core/requestUpdate.ts, src/modules/renderings/laravel/core/resource.ts, src/modules/renderings/laravel/core/route.ts, src/modules/renderings/laravel/core/serviceIndex.ts, src/modules/renderings/laravel/core/serviceStore.ts, src/modules/renderings/laravel/core/serviceUpdate.ts, src/modules/renderings/vue/core/createOrEditMaster.ts, src/modules/renderings/vue/core/datagrid.ts, src/modules/renderings/vue/core/formCreateOrEditMaster.ts, src/modules/renderings/vue/core/routes.ts, src/modules/renderings/vue/core/services.ts, src/modules/renderings/vue/core/tabs.ts, src/modules/renderings/vue/core/types.ts, src/modules/renderings/vue/core/useCreateOrEditMaster.ts, src/modules/renderings/vue/core/useDatagrid.ts, src/processes/writeBackend.ts, src/processes/writeFrontend.ts, src/templates/vue/components/formCreateOrEditMaster, src/templates/vue/composables/useCreateOrEdit, src/templates/vue/services/index, src/templates/vue/views/createOrEditMaster
feat: Array of options in selects.
=> feat: Array of options in selects

src/app.ts, src/customTypes/db.ts, src/templates/laravel/model, src/templates/vue/views/index
=> feat: Add foreign key name

src/templates/vue/composables/useCreateOrEdit, src/templates/vue/routes/index, src/templates/vue/types/index
=> fix: Set typed

src/templates/vue/types/index
feat: Add foreignTableName type.
=> feat: Add foreignTableName type

src/app.ts, src/customTypes/db.ts, src/processes/getCustomData.ts, src/templates/laravel/model
refactor: The main file creating the getCustomData.
=> refactor: The main file creating the getCustomData

src/modules/renderings/laravel/core/controller.ts, src/modules/renderings/laravel/core/model.ts, src/modules/renderings/laravel/core/requestStore.ts, src/modules/renderings/laravel/core/requestUpdate.ts, src/modules/renderings/laravel/core/resource.ts, src/modules/renderings/laravel/core/route.ts, src/modules/renderings/laravel/core/serviceIndex.ts, src/modules/renderings/laravel/core/serviceStore.ts, src/modules/renderings/laravel/core/serviceUpdate.ts, src/modules/renderings/vue/core/createOrEditMaster.ts, src/modules/renderings/vue/core/datagrid.ts, src/modules/renderings/vue/core/formCreateOrEditMaster.ts, src/modules/renderings/vue/core/routes.ts, src/modules/renderings/vue/core/services.ts, src/modules/renderings/vue/core/tabs.ts, src/modules/renderings/vue/core/types.ts, src/modules/renderings/vue/core/useCreateOrEditMaster.ts, src/modules/renderings/vue/core/useDatagrid.ts, src/utils/rendering.ts
refactor: Cores rendering module.
=> refactor: Cores rendering module

src/customTypes/db.ts, src/modules/renderings/vue/core/tabs.ts, src/processes/getCustomData.ts, src/templates/laravel/model, src/templates/vue/components/formCreateOrEditMaster, src/templates/vue/composables/useCreateOrEdit, src/templates/vue/types/index, src/templates/vue/views/index
refactor: Rename columnName to foreignTableName.
=> refactor: Rename columnName to foreignTableName

src/customTypes/utilsRendering.ts, src/processes/getCustomData.ts, src/processes/writeFrontend.ts, src/templates/vue/views/tabs
feat: Start with form master-details.
=> feat: Start with form master-details

src/customTypes/utilsRendering.ts, src/modules/renderings/vue/core/tabDetail.ts, src/modules/renderings/vue/core/tabMaster.ts, src/modules/renderings/vue/index.ts, src/processes/getCustomData.ts, src/processes/writeFrontend.ts, src/templates/vue/components/tabDetail, src/templates/vue/components/tabMaster, src/templates/vue/views/tabs
=> feat: Tab scaffolding

src/modules/renderings/vue/core/servicesDetail.ts, src/modules/renderings/vue/core/typesDetail.ts, src/modules/renderings/vue/core/useTabDetail.ts, src/modules/renderings/vue/core/useTabMaster.ts, src/modules/renderings/vue/index.ts, src/processes/writeFrontend.ts, src/templates/vue/components/formDetail, src/templates/vue/components/formMaster, src/templates/vue/components/tabDetail, src/templates/vue/components/tabMaster, src/templates/vue/components/tableDetail, src/templates/vue/composables/useFormMaster, src/templates/vue/composables/useTabDetail, src/templates/vue/composables/useTabMaster, src/templates/vue/composables/userFormDetail, src/templates/vue/services/detail, src/templates/vue/types/detail
feat: Scaffolding of composables, services and types.
=> feat: Scaffolding of composables, services and types

src/processes/writeBackend.ts, src/processes/writeFrontend.ts
=> refactor: Params all

src/modules/renderings/laravel/core/controller.ts, src/modules/renderings/laravel/core/model.ts, src/modules/renderings/laravel/core/requestStore.ts, src/modules/renderings/laravel/core/requestUpdate.ts, src/modules/renderings/laravel/core/resource.ts, src/modules/renderings/laravel/core/route.ts, src/modules/renderings/laravel/core/serviceIndex.ts, src/modules/renderings/laravel/core/serviceStore.ts, src/modules/renderings/laravel/core/serviceUpdate.ts, src/modules/renderings/vue/core/createOrEditMaster.ts, src/modules/renderings/vue/core/datagrid.ts, src/modules/renderings/vue/core/formCreateOrEditMaster.ts, src/modules/renderings/vue/core/routes.ts, src/modules/renderings/vue/core/services.ts, src/modules/renderings/vue/core/servicesDetail.ts, src/modules/renderings/vue/core/tabDetail.ts, src/modules/renderings/vue/core/tabMaster.ts, src/modules/renderings/vue/core/tabs.ts, src/modules/renderings/vue/core/types.ts, src/modules/renderings/vue/core/typesDetail.ts, src/modules/renderings/vue/core/useCreateOrEditMaster.ts, src/modules/renderings/vue/core/useDatagrid.ts, src/modules/renderings/vue/core/useTabDetail.ts, src/modules/renderings/vue/core/useTabMaster.ts, src/processes/writeBackend.ts, src/processes/writeFrontend.ts
=> refactor: Core rendering

src/modules/renderings/vue/core/formMaster.ts, src/modules/renderings/vue/core/services.ts, src/modules/renderings/vue/core/servicesDetail.ts, src/modules/renderings/vue/core/useFormMaster.ts, src/modules/renderings/vue/index.ts, src/processes/writeFrontend.ts, src/templates/vue/components/formMaster, src/templates/vue/components/tabMaster, src/templates/vue/composables/useFormMaster, src/templates/vue/composables/useIndex, src/templates/vue/composables/useTabMaster
feat: Create composable templates for the master
=> feat: Create composable templates for the master

src/modules/renderings/vue/core/formDetail.ts, src/modules/renderings/vue/core/tableDetail.ts, src/modules/renderings/vue/core/useFormDetail.ts, src/modules/renderings/vue/index.ts, src/processes/writeFrontend.ts, src/templates/vue/components/formDetail, src/templates/vue/components/tabDetail, src/templates/vue/components/tableDetail, src/templates/vue/composables/useFormDetail, src/templates/vue/composables/useTabDetail, src/templates/vue/services/detail
feat: Built scaffold to formDetail, useFormDetail and tableDetail.
=> feat: Built scaffold to formDetail, useFormDetail and tableDetail

src/processes/getDataOfBD.ts
feat: Create tablesStructureOfDetails function
=> feat: Create tablesStructureOfDetails function

src/customTypes/db.ts, src/processes/getCustomData.ts, src/processes/getDataOfBD.ts
feat: Customize structureOfDetails in detailOfMaster.
=> feat: Customize structureOfDetails in detailOfMaster

src/config/output.ts, src/modules/renderings/vue/core/servicesDetail.ts, src/processes/getCustomData.ts, src/processes/writeFrontend.ts, src/templates/vue/composables/useTabDetail, src/templates/vue/composables/useTabMaster
fix: WriteFrontend processes (part two).
=> fix: WriteFrontend processes (part two)

src/templates/vue/components/formDetail, src/templates/vue/components/formMaster, src/templates/vue/components/tabDetail, src/templates/vue/components/tableDetail, src/templates/vue/composables/useFormDetail, src/templates/vue/composables/useTabDetail, src/templates/vue/views/tabs
feat: Render respective fields in formDetails.
=> feat: Render respective fields in formDetails

src/processes/getCustomData.ts, src/templates/vue/components/formDetail
=> feat: Test send function

src/processes/getCustomData.ts, src/templates/laravel/model, src/templates/vue/components/formDetail
feat: Make use of injected functions.
=> feat: Make use of injected functions

src/processes/getCustomData.ts, src/templates/vue/components/formMaster, src/templates/vue/composables/useFormMaster
=> feat: Validate master form

src/templates/vue/components/formMaster, src/templates/vue/components/tabMaster
=> feat: Edit table master

src/processes/getCustomData.ts, src/templates/laravel/model
=> feat: Model hasMany relation

src/customTypes/utilsRendering.ts, src/modules/renderings/laravel/core/modelDetail.ts, src/modules/renderings/laravel/index.ts, src/processes/getCustomData.ts, src/processes/writeBackend.ts, src/templates/laravel/modelDetail
=> feat: Build detail models

src/modules/renderings/laravel/core/controllerDetail.ts, src/modules/renderings/laravel/core/routeDetail.ts, src/modules/renderings/laravel/index.ts, src/processes/getCustomData.ts, src/processes/writeBackend.ts, src/templates/laravel/controllerDetail, src/templates/laravel/routeDetail, src/templates/vue/components/tableDetail, src/templates/vue/services/detail
=> feat: Render detail tables

src/processes/getCustomData.ts, src/templates/laravel/controllerDetail, src/templates/laravel/model, src/templates/laravel/modelDetail, src/templates/laravel/requestStore, src/templates/laravel/requestUpdate, src/templates/vue/components/formDetail, src/templates/vue/views/index, src/utils/fn.ts, src/utils/nomenclature.ts
=> refactor: getCustomData

src/modules/renderings/laravel.ts, src/processes/writeBackend.ts, src/templates/laravel/storeDetailRequest, src/templates/laravel/storeDetailService, src/templates/laravel/updateDetailRequest, src/templates/laravel/updateDetailService
feat: storeDetailService & updateDetailService.
=> feat: storeDetailService & updateDetailService

src/templates/laravel/storeDetailService, src/templates/vue/components/formDetail, src/templates/vue/components/tableDetail, src/templates/vue/composables/useTabDetail
=> fix: Insert details records

src/templates/vue/components/formDetail, src/templates/vue/components/tabDetail, src/templates/vue/composables/useTabDetail
feat: Validate toggle details panel.
=> feat: Validate toggle details panel

src/templates/vue/components/tabDetail, src/templates/vue/composables/useTabDetail
refactor: panelToogle method of details to composables.
=> refactor: panelToogle method of details to composables

src/processes/writeFrontend.ts, src/templates/vue/components/formCreateOrEditMaster, src/templates/vue/components/formDetail, src/templates/vue/components/tableDetail, src/templates/vue/composables/useFormDetail, src/templates/vue/composables/useTabDetail, src/templates/vue/services/detail, src/templates/vue/types/detail, src/templates/vue/types/index
feat: Types of details & fix: Other types
=> feat: Types of details & fix: Other types

src/customTypes/db.ts, src/processes/getCustomData.ts, src/processes/getDataOfBD.ts, src/templates/vue/components/formDetail, src/templates/vue/composables/useFormDetail
feat: Create tableDetailForeignKeysHelp function.
=> feat: Create tableDetailForeignKeysHelp function

src/processes/getCustomData.ts, src/templates/laravel/serviceIndex, src/utils/fn.ts
fix: Basic search in the index datatable.
=> fix: Basic search in the index datatable

src/templates/laravel/model, src/templates/laravel/modelDetail, src/templates/laravel/requestStore, src/templates/laravel/requestUpdate, src/templates/laravel/serviceIndex, src/templates/laravel/storeDetailRequest, src/templates/laravel/storeDetailService, src/templates/laravel/updateDetailRequest, src/templates/laravel/updateDetailService, src/templates/vue/composables/useTabDetail, src/utils/fn.ts
refactor: Utility validator functions.
=> refactor: Utility validator functions

package-lock.json, package.json, src/templates/laravel/model, src/templates/laravel/modelDetail, src/templates/laravel/requestStore, src/templates/laravel/requestUpdate, src/templates/laravel/storeDetailRequest, src/templates/laravel/updateDetailRequest, src/utils/__tests__/fn/addCommaToArr.spec.ts, src/utils/__tests__/fn/excludeFields.spec.ts, src/utils/__tests__/fn/noId.spec.ts, src/utils/__tests__/fn/noIdAndExcludeFields.spec.ts, src/utils/__tests__/nomenclature.spec.ts, src/utils/fn.ts
refactor: Add automated tests.
=> refactor: Add automated tests

package-lock.json, package.json, src/utils/__tests__/createOutputPath.spec.ts, src/utils/__tests__/rendering.spec.ts, src/utils/createOutputPath.ts, src/utils/excludeFiles.ts, src/utils/nomenclature.ts, src/utils/rendering.ts
refactor: createOutputPath test.
=> refactor: createOutputPath test

src/utils/__tests__/rendering.spec.ts
=> fix: Finish rendering test

src/app.ts, src/templates/laravel/modelDetail, src/templates/vue/components/tableDetail
feat: Show tableForeignKeysAssoc in details tables.
=> feat: Show tableForeignKeysAssoc in details tables

src/core/types/db.ts, src/core/utils/fn.ts, src/stack/templates/vue/components/formCreateOrEditMaster, src/stack/templates/vue/components/formDetail, src/stack/templates/vue/components/formMaster, src/stack/templates/vue/components/tabDetail, src/stack/templates/vue/composables/useTabMaster
=> fix: Various fixes

src/stack/templates/vue/views/tabs
feat: Do not load details components when creating master record.
=> feat: Do not load details components when creating master record

.env.example, src/core/config/output.ts, src/core/utils/createOutputPath.ts, src/core/utils/rendering.ts
feat: Make path root configurable.
=> feat: Make path root configurable

package.json, src/app.ts, src/core/types/consoleLog.ts, src/core/utils/consoleLog.ts, tsconfig.json
refactor: Add processes to core folder paths configuration.
=> refactor: Add processes to core folder paths configuration

package.json, src/app.ts, src/config/db.ts, src/config/index.ts, src/core/index.ts, src/core/modules/db.ts, src/core/processes/getCustomData.ts, src/core/processes/getDataOfBD.ts, src/stack/index.ts, src/stack/processes/laravel.ts, src/stack/renderings/laravel.ts, src/stack/renderings/vue.ts, tsconfig.json
refactor: Core import-export structure.
=> refactor: Core import-export structure

src/app.ts
feat: Custom log console function.
=> feat: Custom log console function

src/app.ts, src/core/index.ts, src/core/processes/main.ts
refactor: Encapsulate the main function.
=> refactor: Encapsulate the main function

src/config/db.ts, src/config/index.ts, src/core/modules/db.ts, src/stack/my-laravel-backend/templates/model, src/stack/my-laravel-backend/templates/requestStore, src/stack/my-laravel-backend/templates/requestUpdate
refactor: Remove DB instance from config and fix: Comma separators are missing.
=> refactor: Remove DB instance from config and fix: Comma separators are missing

src/app.ts, src/config/index.ts, src/core/modules/db.ts, src/core/processes/getCustomData.ts, src/core/processes/getDataOfBD.ts, src/core/processes/main.ts, src/core/types/config.ts, src/stack/my-laravel-backend/process.ts, src/stack/my-laravel-backend/renderings.ts, src/stack/my-vue-frontend/process.ts, src/stack/my-vue-frontend/renderings.ts
refactor: Pass config object through main process.
=> refactor: Pass config object through main process

src/core/types/rendering.ts, src/core/utils/rendering.ts, src/stack/my-laravel-backend/process.ts, src/stack/my-laravel-backend/renderings.ts, src/stack/my-vue-frontend/process.ts, src/stack/my-vue-frontend/renderings.ts
fix: Pass config object through main process.
=> fix: Pass config object through main process

package.json, tsconfig.json
=> refactor: Remove core alias

src/stack/my-vue-frontend/templates/components/formMaster
refactor: Implement fn.foreignTableName.
=> refactor: Implement fn.foreignTableName

src/stack/my-backend-example/process.ts, src/stack/my-backend-example/renderings.ts, src/stack/my-backend-example/templates/controller, src/stack/my-backend-example/templates/model, src/stack/my-backend-example/templates/route, src/stack/my-frontend-example/process.ts, src/stack/my-frontend-example/renderings.ts, src/stack/my-frontend-example/templates/masterCreateOrEdit, src/stack/my-frontend-example/templates/masterDatagrid, src/stack/my-frontend-example/templates/masterForm
=> feat: Create stack example

src/stack/my-frontend-example/templates/masterDatagrid
feat: Build masterDatagrid template.
=> feat: Build masterDatagrid template

src/stack/my-frontend-example/templates/masterCreateOrEdit, src/stack/my-frontend-example/templates/masterForm
feat: Build masterCreateOrEdit and masterForm templates.
=> feat: Build masterCreateOrEdit and masterForm templates

.env.example
=> chore: Change preset example
